version: '3.9'


services:
  api:
    build: .
    platform: linux/arm64/v8
    command:
      - /bin/bash
      - -c
      - |
        uvicorn app.main:app --host 0.0.0.0 --port 8200 --reload --log-config logger_config.yaml
    volumes:
      - .:/code
    ports:
      - '8000:8000'